
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: 'root'
  password: ''
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: develop


production:
  <<: *default
  database: production
